//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rogernoob
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        public clients()
        {
            this.factura = new HashSet<factura>();
        }
    
        public int id_Client { get; set; }
        public string Nom { get; set; }
        public string Cognom1 { get; set; }
        public string Cognom2 { get; set; }
        public string Adreça { get; set; }
        public int Codi_Postal { get; set; }
        public string Població { get; set; }
        public string Província { get; set; }
        public Nullable<int> Telèfon { get; set; }
        public Nullable<int> Fax { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<factura> factura { get; set; }
    }
}
