//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rogernoob
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura_detall
    {
        public int n_Factura { get; set; }
        public int id_Producte { get; set; }
        public Nullable<int> Quantitat { get; set; }
    }
}
