//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rogernoob
{
    using System;
    using System.Collections.Generic;
    
    public partial class productes
    {
        public int id_Producte { get; set; }
        public string Producte { get; set; }
        public Nullable<decimal> Preu { get; set; }
    }
}
